### ISSUE TITLE
MCP SDK Can not handle the MCP Servers with subpath

### ISSUE THREAD

**Issue by tobegit3hub** [jlowin/fastmcp#530]
### Description

**Issue:**  
Clients (Inspector/Cherry Studio) fail to connect when MCP Server uses a subpath (e.g., `http://domain.com/subpath/sse`). Root paths (`http://domain.com/`) work normally.

**Reproduce:**  
1. Start MCP Server at `http://domain.com/subpath/sse`  
2. Client connection fails with error:  
   `Error POSTing to endpoint (HTTP 503): no healthy upstream`  

**Cause:**  
In [`sse.ts#L146`](https://github.com/modelcontextprotocol/typescript-sdk/blob/main/src/client/sse.ts#L146), `new URL()` discards the subpath from the server URL. Example:  
Request to `/messages/` becomes `http://domain.com/messages/` instead of `http://domain.com/subpath/messages/`.

### Example Code

```Python

```

### Version Information

```Text
1.5.0
```

**Comment by jlowin** [comment]
This bug is fixed in FastMCP 2.0 (which is this repo). I'm not sure what 1.5 is, we never released that version.

**Comment by tobegit3hub** [comment]
@jlowin  Sorry for the misleading version. I hava upgrade `fastmcp` to 2.3.5 and still get the absolute path of `/messages/`.

<img width="527" alt="Image" src="https://github.com/user-attachments/assets/aa823896-266b-4f1c-ae39-da0fb0685719" />
