### ISSUE TITLE
Does not work with browser based MCP clients due to lack of CORS support

### ISSUE THREAD

**Issue by radiantone** [jlowin/fastmcp#840]
### Description

Does not work with browser based MCP clients due to lack of CORS support

### Example Code

```Python

```

### Version Information

```Text
Should allow for CORS header config to support browser clients
```

**Comment by Sillocan** [comment]
You can add CORS support via Starlette Middleware. The docs has an example of exactly this use case: https://gofastmcp.com/deployment/asgi#custom-middleware

**Comment by monarchwadia** [comment]
This is also not working for me.

I'm using the following cURL call to reproduce

We are using uvicorn as the middleware.'

Preflight request on OPTIONS is failing, which means we can't do POST from a browser.

# Without trailing slash

This one is without a trailing slash on the `/mcp` route

```sh
curl -X OPTIONS http://localhost:8000/mcp \
  -H "Origin: http://localhost:3000" \
  -H "Access-Control-Request-Method: POST" \
  -H "Access-Control-Request-Headers: Content-Type, Authorization" \
  -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36" \
  -v
* Host localhost:8000 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8000...
* connect to ::1 port 8000 from ::1 port 60812 failed: Connection refused
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000
> OPTIONS /mcp HTTP/1.1
> Host: localhost:8000
> Accept: */*
> Origin: http://localhost:3000
> Access-Control-Request-Method: POST
> Access-Control-Request-Headers: Content-Type, Authorization
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36
> 
< HTTP/1.1 307 Temporary Redirect
< date: Mon, 16 Jun 2025 17:11:47 GMT
< server: uvicorn
< access-control-allow-origin: *
< access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
< access-control-allow-headers: *
< access-control-allow-credentials: true
< allow: GET, POST, PUT, DELETE, OPTIONS
< content-length: 0
< location: http://localhost:8000/mcp/
< 
* Connection #0 to host localhost left intact
```

# With trailing slash

Notice that in the previous call, the Location for the 307 is `http://localhost:8000/mcp/`, with a trailing slash

When I try to use that, then I get another error

```sh
curl -X OPTIONS http://localhost:8000/mcp/   -H 
"Origin: http://localhost:3000"   -H "Access-Control-Request-Method: POST"   -H "Access-Control-Request-Headers: Conten
t-Type, Authorization"   -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36"   -v
* Host localhost:8000 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8000...
* connect to ::1 port 8000 from ::1 port 43164 failed: Connection refused
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000
> OPTIONS /mcp/ HTTP/1.1
> Host: localhost:8000
> Accept: */*
> Origin: http://localhost:3000
> Access-Control-Request-Method: POST
> Access-Control-Request-Headers: Content-Type, Authorization
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36
> 
< HTTP/1.1 405 Method Not Allowed
< date: Mon, 16 Jun 2025 17:12:57 GMT
< server: uvicorn
< access-control-allow-origin: *
< access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
< access-control-allow-headers: *
< access-control-allow-credentials: true
< allow: GET, POST, PUT, DELETE, OPTIONS
< content-type: application/json
< allow: GET, POST, DELETE
< mcp-session-id: f7029403895b4110902a414e10ba463e
< content-length: 92
< 
* Connection #0 to host localhost left intact
{"jsonrpc":"2.0","id":"server-error","error":{"code":-32600,"message":"Method Not Allowed"}}
```

**Comment by monarchwadia** [comment]
Some additional info for you, just in case it helps?

https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

^ Preflight requests need to be supported in order to support browser.

This is the blocker I'm experiencing... preflight is failing.

**Comment by jlowin** [comment]
I agree, I think this is a deployment concern for the ASGI app (which should accept all standard CORS configuration), not the MCP server, but if it becomes a common enough impediment we could look at a shortcut for adding CORS. I'm not sure how much more simple we can make it, though, without opening up a new set of enhancement requests for customization. Even FastAPI doesn't have a one-liner for CORS enablement.

**Comment by radiantone** [comment]
> You can add CORS support via Starlette Middleware. The docs has an example of exactly this use case: https://gofastmcp.com/deployment/asgi#custom-middleware

That example still didn't work. I had to do some api gymnastics to get the preflight to work.

```python
from fastmcp import FastMCP
from fastapi import FastAPI

from starlette.middleware import Middleware
from starlette.middleware.cors import CORSMiddleware
from starlette.applications import Starlette
from starlette.routing import Mount

# Create your FastMCP server
mcp = FastMCP("MyServer")

mcp_app = mcp.http_app(path='/mcp')
starlette = Starlette(
    routes=[
        Mount("/", app=mcp_app),
        # Add other routes as needed
    ],
    lifespan=mcp_app.lifespan,
)
app = FastAPI(lifespan=mcp_app.lifespan)
app.mount("/", starlette)

origins = [
    "http://localhost",
    "http://localhost:8080"
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,  # List of allowed origins
    allow_credentials=True,  # Allow cookies and authorization headers
    allow_methods=["*"],     # Allow all HTTP methods (GET, POST, PUT, DELETE, etc.)
    allow_headers=["*"],     # Allow all headers
)

@mcp.tool()
def greet(name: str) -> str:
    """
    Greets the person passed in the name parameter
    """
    return f"Hello, {name}!"

if __name__ == "__main__":
    mcp.run()
```

**Comment by jlowin** [comment]
Thanks for raising this issue\! You were absolutely right - the CORS documentation example was incomplete and didn't properly handle browser preflight requests.

The problem was that the original example only allowed `GET` methods, but browsers send `OPTIONS` preflight requests with `Access-Control-Request-Method: POST` for MCP calls, which were being rejected with "Disallowed CORS method".

I've just fixed the documentation in #894 to include the complete CORS configuration needed:

```python
custom_middleware = [
    Middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_credentials=True,
        allow_methods=["*"],  # Critical: allows POST/OPTIONS
        allow_headers=["*"],  # Critical: allows Content-Type
    ),
]
```

This should resolve the preflight issues you and @monarchwadia encountered. The middleware functionality itself works correctly - it was just the documentation example that was missing the required parameters.

**Comment by jlowin** [comment]
Thanks for raising this issue\! You were absolutely right - the CORS documentation example was incomplete and didn't properly handle browser preflight requests.

I've just fixed the documentation in #895 to include the complete CORS configuration needed.

This should resolve the preflight issues you and @monarchwadia encountered. The middleware functionality itself works correctly - it was just the documentation example that was missing the required parameters.

**Comment by radiantone** [comment]
Thanks I will try it again with my browser MCP client.

**Comment by radiantone** [comment]
@jlowin Hi. I tried accessing fastmcp server from browser and it still does not work. The reason is that FastMCP server sets the referrer policy to be strict-origin-when-cross-origin. This will prevent any 3rd party webapp from talking to the MCP server. The whole point of MCP servers is for 3rd party apps to connect to them.

Request URL http://127.0.0.1:8000/mcp
Referrer Policy strict-origin-when-cross-origin

Browser error:
Access to fetch at 'http://127.0.0.1:8000/mcp' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.Understand this error

**Comment by radiantone** [comment]
If there is an example somewhere (in your tests maybe) that can prove or demonstrate how fastmcp server can be connected to from browser, then do please share. Based on my findings, this is not the case which breaks the MCP paradigm.

**Comment by Sillocan** [comment]
@radiantone  The docs referenced above show examples. I guarantee you this works with browsers as I use it everyday. 

Your example doesn't work because you are using mcp.run() which isn't the app you mount cors middleware to.

**Comment by alosorioc** [comment]
Hi, 
I'm using code provided by @jlowin in examples, but not able to connect to the server from client application:

**Server code**
`import datetime
import time
import uvicorn

from pydantic import Field
from fastmcp import FastMCP
from starlette.requests import Request
from starlette.middleware import Middleware
from typing import Dict, Optional, Annotated
from starlette.responses import PlainTextResponse
from starlette.middleware.cors import CORSMiddleware

# Create MCP Server
mcp = FastMCP(name="MCPServer", cache_expiration_seconds=300)


@mcp.custom_route("/mcpserver/", methods=["GET"])
@mcp.custom_route("/mcpserver/healthcheck", methods=["GET"])
def healthcheck(request: Request) -> PlainTextResponse:
    '''
    healthcheck: necessary for Kubernetes deployments.
    '''
    return PlainTextResponse("OK")


@mcp.tool (tool definitions)
...
    

# CORS configuration
ALLOWED_ORIGINS = config.ALLOWED_ORIGINS

# Define custom middleware
custom_middleware = [
    Middleware(
        CORSMiddleware,
        allow_origins=ALLOWED_ORIGINS,
        allow_credentials=True,
        allow_methods=["GET", "POST", "OPTIONS"],
        allow_headers=["Content-Type", "Authorization"],
    ),
]

# Create ASGI app with custom middleware
http_app = mcp.http_app(
    transport="http",
    path="/mcpserver/mcp",
    middleware=custom_middleware
)
    

if __name__ == "__main__":
    Logger.info(f"Starting MCP server on port {config.PORT}")
    try:
        uvicorn.run(http_app, host=config.HOST, port=config.PORT)
    except Exception as e:
        Logger.exception("Error running MCP server")
        raise`

**Client code:**
`from agents.mcp import MCPServerStreamableHttp
...
mcp_server = MCPServerStreamableHttp(
                name="MCP Server",
                client_session_timeout_seconds=60,
                cache_tools_list=True,
                params={
                    "url": Config['MCP_SERVER_URL'],
                    "headers": {
                        "Accept": "application/json, text/event-stream",
                        "Content-Type": "application/json"
                    }
                }
            )

try:
                log_info(f"Establishing connection with MCP server.")
                await mcp_server.connect() # EXCEPTION raised here!!
                log_info(f"Connected to MCP server ({Config['MCP_SERVER_URL']})")
except Exception as e:
`
**RuntimeWarning: coroutine '_MCPServerWithClientSession.list_tools' was never awaited
  self._variable_reference_to_variable.clear()**

Not sure if this is related to the CORS issue or something else. If I change my server to SSE it is working as expected.
Appreciate your comments or suggestions.
Thanks

**Comment by radiantone** [comment]
> [@radiantone](https://github.com/radiantone) The docs referenced above show examples. I guarantee you this works with browsers as I use it everyday.
> 
> Your example doesn't work because you are using mcp.run() which isn't the app you mount cors middleware to.

What browser mcp client are you using?

**Comment by Sillocan** [comment]
https://github.com/modelcontextprotocol/typescript-sdk

**Comment by SmartManoj** [comment]
Shouldn't CORS be enabled by default?

https://github.com/punkpeye/fastmcp/commit/fe39e7a1d5651b0fda966177c52d18ea31cafadf

**Comment by radiantone** [comment]
> https://github.com/modelcontextprotocol/typescript-sdk
> […](#)

When I use that client package with my code above (I run it with ( uvicorn main:app ) I get this error.


{jsonrpc: "2.0", id: "server-error", error: {code: -32600, message: "Bad Request: Missing session ID"}}
error
: 
{code: -32600, message: "Bad Request: Missing session ID"}
code
: 
-32600
message
: 
"Bad Request: Missing session ID"
id
: 
"server-error"
jsonrpc
: 
"2.0"

and my MCP client code is this:

    let client = new Client({
      name: 'streamable-http-client',
      version: '1.0.0'
    });
    const transport = new StreamableHTTPClientTransport('http://127.0.0.1:8000/mcp');
    await client.connect(transport);
    console.log('CLIENT', client);
    const prompts = await client.listPrompts();
    console.log('PROMPTS', prompts);

**Comment by djpirra** [comment]
Also having CORS issues. Was this solved? How to implement the server using CORS and streamable HTTP?

**Comment by MaxwellKendall** [comment]
seems like we should not use `mcp.run()` in production? I'm still seeing CORS errors when I'm hosted in mcp.cloud but locally when I hit my server at an ngrok url (tunneling my local process to a public url), I dont see any errors even with mcp.run

**Comment by hyajam** [comment]
This fixed my issue:

```python
import uvicorn
from starlette.middleware.cors import CORSMiddleware
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("Weather", stateless_http=True, json_response=True)

@mcp.tool()
async def get_weather(location: str) -> str:
    """Get weather for location."""
    return "It's always sunny in New York"

if __name__ == "__main__":
    # Get the Starlette app for streamable HTTP
    starlette_app = mcp.streamable_http_app()

    starlette_app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],  # Allow all origins for development; restrict in production
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # Run the server
    uvicorn.run(starlette_app, host="127.0.0.1", port=8000)
```

**Comment by DaStru** [comment]
The example by @hyajam no longer works because `streamable_http_app()` was removed in [v2.14.0](https://github.com/jlowin/fastmcp/pull/2336). 

Below is a current example of enabling CORS for FastMCP, including a fix for the ["Missing session ID"](https://github.com/modelcontextprotocol/python-sdk/issues/808#issuecomment-2914415233) error in MCP Inspector by exposing the `mcp-session-id` header.

```python
import uvicorn
from fastmcp import FastMCP
from starlette.middleware.cors import CORSMiddleware

mcp = FastMCP(name="Weather")

@mcp.tool()
async def get_weather(location: str) -> str:
    """Get weather for location."""
    return f"It's always sunny in {location}"

# Create HTTP app and enable CORS
app = mcp.http_app(path="/mcp")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],         # Adjust as needed
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["mcp-session-id"]  # Fixes "Missing session ID" in MCP Inspector
)

if __name__ == "__main__":
    uvicorn.run(app, host="localhost", port=8000)
```
